### ISSUE TITLE
openvino_inference.py reporting KeyError: '64'

### ISSUE THREAD

**Issue by tarekradi** [oneapi-src/visual-quality-inspection#4]
Why is this failing? How can i fix this? Thanks!

![image](https://user-images.githubusercontent.com/13227624/199779215-02949a75-3494-405b-8ba9-4c9a7a48ffb5.png)

**Comment by tarekradi** [comment]
FYI, here is the flow i am using:
1) training using python src/training.py --datapath /data/pill-data --outmodel pill_intel --dataaug 0 --hyperparams 0 --intel 0
2) inferring using python src/intel_openvino/openvino_inference.py --model /input/train/pill_intel_model.onnx --input /data/pill-data/test/good

What am i doing wrong?

**Comment by tarekradi** [comment]
Note that when training, i see the following.... Is this contributing to the problem?

![image](https://user-images.githubusercontent.com/13227624/199781289-93611870-a0c5-4eb3-aaa7-56fd64b1b12d.png)

**Comment by tarekradi** [comment]
by the way, here is the version of openvino that i am running 
![image](https://user-images.githubusercontent.com/13227624/199874818-bdc03eb0-8053-40f2-ac6c-006a4b701390.png)

**Comment by tarekradi** [comment]
When i uninstall that version and install version 2021.4.2, i still get the same error...
![image](https://user-images.githubusercontent.com/13227624/199875090-b8d0e513-2b1e-45fc-87b2-5292375bb168.png)

**Comment by tarekradi** [comment]
by the way, if i comment out this line from openvino_inference.py
   net.outputs[out_blob].precision = 'FP32'
I run into similar problems with the out_blob in training.py. 

There seems to be an issue with IECore, because inference_engine = IECore(), and we use that engine to read the network and load it up as "net". Maybe net never got an out_blob?

**Comment by huiyan2021** [comment]
Hi @tarekradi, OpenVINO 2021.4 is used in this reference kit, there is a PR upgrading to 2022.1, https://github.com/oneapi-src/visual-quality-inspection/pull/3/files#diff-235eeb2b73888a769fa4f3742b20a56fafafad8f925ebbacf6cdbb6085ac853e, you may refer to that for 2022.2

**Comment by tarekradi** [comment]
Hi, please note that as i mentioned in this ticket, this does not work using 2021.4.2 and does not work using 2022.2.0. I really don't care which version of OpenVINO to use. I just want this to work. Currently, it is not working and complains about KeyError="64". Please see screenshots. Thanks

**Comment by huiyan2021** [comment]
Sorry for not noticing that you tried OpenVINO 2021.4...

net.outputs[out_blob].precision = 'FP32'
KeyError:'64'
It means there is no output node named '64' in your model.

In the reference kit, we are using
- pytorch==1.8.0
- torchvision=0.9.0
seems that you are using higher version, I tried the latest version and got the same issue.

You can open the pill_intel_model.onnx using Netron, check the output node name, and pass it to --outputname argument when running openvino_inference.py
in my case, in the model trained by torch 1.13.0, the output node name is '66', below command works: 
python src/intel_openvino/openvino_inference.py --model ./pill_intel_model.onnx --input ./data/test/good **--outputname '66'**

![image](https://user-images.githubusercontent.com/88080182/200747679-3418c371-f7a9-4747-8bda-9368ec4a24ba.png)

**Comment by tarekradi** [comment]
thank you very much. In my case, the softmax output node was 65
![image](https://user-images.githubusercontent.com/13227624/200879751-100fb172-5ed3-4654-95e5-faa97f71998d.png)

I added outputname as a parameter for openvino_inference.py in cnvrg
![image](https://user-images.githubusercontent.com/13227624/200880140-f928b311-4725-49c2-8f39-b0e05b09502a.png)

I am running the entire flow now. 
![image](https://user-images.githubusercontent.com/13227624/200880201-cc7061b0-b33c-4c32-99a1-5968c119e418.png)

I'll report back on results. Thanks.

**Comment by tarekradi** [comment]
Thank you. This worked. Much appreciated!!! You can close this ticket now, but please update the documentation of the reference kit to indicate this. I don't think people who use the reference kit will be able to find this out easily. Thanks!

**Comment by huiyan2021** [comment]
This issue should be not there anymore after the PR: https://github.com/oneapi-src/visual-quality-inspection/pull/3/files#diff-235eeb2b73888a769fa4f3742b20a56fafafad8f925ebbacf6cdbb6085ac853e is merged, thanks!

**Comment by tarekradi** [comment]
What is a PR? Sorry, i am not familiar with that acronym. Shall i go ahead and integrate this patch in my code? What does it do other than fix this issue?
